### ISSUE TITLE
HttpRequest.sendPost is deprecated

### ISSUE THREAD

**Issue by neeravagarwalmicrosoft** [AzureAD/microsoft-authentication-library-common-for-android#1037]
Need to take care of this deprecation at following places:

1. In class "OAuth2Strategy", method "performTokenRequest"
2. In class "OAuth2Strategy", method "getDeviceCode"
3. In class "MicrosoftStsOAuth2Strategy", method "performPKeyAuthRequest"

Package of HttpRequest: com.microsoft.identity.common.internal.net

**Comment by AdamBJohnsonx** [comment]
We should migrate these to an HttpClient derivative instead.

**Comment by AdamBJohnsonx** [comment]
We should migrate these to an HttpClient derivative instead.

**Comment by iambmelt** [comment]
ADO Tracking (corpnet reqd):
- https://identitydivision.visualstudio.com/Engineering/_workitems/edit/1226171
