### ISSUE TITLE
HttpRequest.sendGet is deprecated

### ISSUE THREAD

**Issue by neeravagarwalmicrosoft** [AzureAD/microsoft-authentication-library-common-for-android#1038]
Need to take care of this deprecation at following places:

1. In class "AzureActiveDirectory", method "performCloudDiscovery"
2. In class "OpenIdProviderConfigurationClient", method "loadOpenIdProviderConfiguration"

Package of HttpRequest: com.microsoft.identity.common.internal.net

**Comment by iambmelt** [comment]
ADO Tracking Info (corpnet reqd):
- https://identitydivision.visualstudio.com/Engineering/_workitems/edit/1226170
