### ISSUE TITLE
Not trimming both comparing keys causes test failure in MSAL xplat test case

### ISSUE THREAD

**Issue by PetarSDimov** [AzureAD/microsoft-authentication-library-common-for-android#1186]
There is a ReadCredentials integration xplat test in MSAL that verifies that code correctly find the credential when keys have different cases or leading or trailing white spaces. The test case randomizes the casing on write as well as on read.
After debugging I believe the issue is in the following helper function in StringUtils

    public static boolean equalsIgnoreCaseTrim(@Nullable String one, @Nullable String two) {
        return one == two || equalsIgnoreCase(one, two.trim());
    }

I believe that the issue will be fixed if we also trim the first parameter in the comparison.

**Comment by iambmelt** [comment]
I'll pick this up, @PetarSDimov if you could provide a sample of failing input

**Comment by iambmelt** [comment]
Closed by #1228
