### ISSUE TITLE
Remove trace logging using Logger.entering/Logger.exiting

### ISSUE THREAD

**Issue by iambmelt** [AzureAD/microsoft-authentication-library-common-for-android#123]
Trace logging in the cache cannot use the `allowPii` switch -- under no circumstances can this data be emitted due to the risk that function inputs/outputs may contain sensitive data such as tokens or key material.

I am going to plumb-out this logic until fine grain logging can be approached with a more security conscious design.

**Comment by heidijinxujia** [comment]
Good to know. Should we apply "remove logging for tokens" in MSAL/ADAL as well? I think we treat the tokens as PII and logged them some places before.

**Comment by iambmelt** [comment]
@heidijinxujia Yeah, we can't do this. @addev-ashish has been sorting this out. If you're aware of anywhere this is still happening, we need to jump on it asap
