### ISSUE TITLE
RTs with family_id must set foci-<id> as cache key value

### ISSUE THREAD

**Issue by iambmelt** [AzureAD/microsoft-authentication-library-common-for-android#148]
Spec-miss discovered while reviewing w/ @addev-ashish 

RTs with a `family_id` must set `foci-<id>` as their cache key value (in lieu of `client_id`)

**Comment by shoatman** [comment]
That's for ADAL... is it not?  What's proposed here?

**Comment by iambmelt** [comment]
This is for common cache in general -- FRT cache keys shouldn't contain the client id, but should instead be "foci-" + family I'd. #149 makes this change

**Comment by shoatman** [comment]
So that's what the unified cache spec says to do?

**Comment by iambmelt** [comment]
The spec is vague on this point, I posted a question in #149 for someone to address. Not sure if this is a gap or if it's just me who's unclear
