### ISSUE TITLE
Anonymous TypeToken instance to get Type instances is unsafe

### ISSUE THREAD

**Issue by ZacSweers** [AzureAD/microsoft-authentication-library-common-for-android#1485]
While updating to AGP 7.0.0 and its new embedded R8 version, I've noticed that it is much stricter about how it optimizes generics. In testing I found that the common GSON pattern of creatining anonymous `TypeToken` instances to get a type is problematic for this. I noticed this SDK uses this pattern in several places and would recommend switching to Gson's newer `TypeToken.getParameterized()` API instead. I can send a PR too if you'd rather.

![image](https://user-images.githubusercontent.com/1361086/127420510-6d7f1b88-1e06-452f-8bb9-1f14474ebc61.png)

**Comment by gitaumoses4** [comment]
Released in [v3.6.2](https://github.com/AzureAD/microsoft-authentication-library-common-for-android/releases/tag/v3.6.2)
