### ISSUE TITLE
Your app contains a less secure encryption mode

### ISSUE THREAD

**Issue by NLLAPPS** [AzureAD/microsoft-authentication-library-common-for-android#1658]
I use MS Graph in my apps and I get "Unsafe Cipher Mode" warning on Google Play for this https://github.com/AzureAD/microsoft-authentication-library-common-for-android/blob/44768f5a94616ff631f76461e89167e28d785749/common/src/main/java/com/microsoft/identity/common/adal/internal/cache/StorageHelper.java#L321
Please see attached screenshot. Article Google is punting is at https://support.google.com/faqs/answer/10046138
![Screenshot 2021-12-16 131705](https://user-images.githubusercontent.com/14060247/146378981-deb25b36-6357-4f2a-82f3-71af82f024a3.jpg)

**Comment by luethib** [comment]
same issue here, seems to be an issue of `CIPHER_ALGORITHM_FOR_KEY_TRACKING = "AES/ECB/PKCS5Padding";` as AES/ECB is considered unsafe. Eventually also affects `KEYSPEC_ALGORITHM = "AES";` and `CIPHER_ALGORITHM = "AES/CBC/PKCS5Padding"`

**Comment by luethib** [comment]
dublicate from [https://github.com/AzureAD/microsoft-authentication-library-common-for-android/issues/1646](https://github.com/AzureAD/microsoft-authentication-library-common-for-android/issues/1646) may be fixed by #1654
