### ISSUE TITLE
Unsafe Cipher Mode Reported by Google Playstore

### ISSUE THREAD

**Issue by guru2010j** [AzureAD/microsoft-authentication-library-common-for-android#1848]
Hello Team,

We have a Security and trust issue reported by google on the pre-launch report. We are requesting to verify and rectify this issue.

Unsafe Cipher Mode

Your app contains a less secure encryption mode. Please see [this Google Help Center article](https://support.google.com/faqs/answer/10046138) for details.

com.microsoft.identity.common.adal.internal.cache.StorageHelper.getKeyThumbPrint

**Comment by tanmaymanolkar1** [comment]
@negoe we should buble up this issue with priority

**Comment by tanmaymanolkar1** [comment]
if this is ADAL app could you please check if you can upgrade to MSAL and if the same issue still persists?

**Comment by guru2010j** [comment]
> if this is ADAL app could you please check if you can upgrade to MSAL and if the same issue still persists?

Hello @tanmaymanolkar1 ,

Thank you so much for your response.

We are currently using MSAL dependency.

com.microsoft.identity.client:msal:2.0.12

**Comment by pallavmitianster** [comment]
Hi @tanmaymanolkar1  Please provide update . We are already using MSAL . TIA

**Comment by guru2010j** [comment]
We have upgraded to MSAL-2.2.3 version as suggested and the issue was resolved in Google reports.

Requesting to close this ticket.
