### ISSUE TITLE
Huawei Device returns null when webpage back button clicked

### ISSUE THREAD

**Issue by heidijinxujia** [AzureAD/microsoft-authentication-library-common-for-android#295]

**Comment by heidijinxujia** [comment]
if clicked 'back' button in the webpage, return "access_denied, null"

**Comment by heidijinxujia** [comment]
seems by design. Do we need to extract the error_subcode?
```
Server Response Url:
$redirect_uri$?error=access_denied&
**error_subcode=cancel**&
state=mty4zthkntytn2ezyy00ndfllwizzgqty2uzzdm4odg2mwnmltixowjmztizlti2nzqtndixoc04zdkwltixzjm1mwrlmzuyng&
add_account=
```

**Comment by heidijinxujia** [comment]
Different from the [doc of V2](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow). In fact, no `error_description` returned and `error_subcode` is returned instead.

**Comment by shoatman** [comment]
This looks like a potential bug for the server team.  We may wan to file this under the convergence epic as a bug for Shiung.
