### ISSUE TITLE
Clear SSO token

### ISSUE THREAD

**Issue by Glennmen** [AzureAD/microsoft-authentication-library-common-for-android#332]
I also want to add this here as (I think) this also requires changes in the `common` library (original issue AzureAD/microsoft-authentication-library-for-android#426).

### Description
Once a user disconnects (`removeAccount()`) the SSO token is still valid in the webview and will be shown on next sign in. I can't find any function to clear webview cookies/data.
This isn't very safe for shared devices, my use-case.

### Use-case
The app itself is a whiteboard app that is installed on big touch screen devices that are used in schools or in meeting rooms. I use MSAL and Microsoft Graph for the build in email export feature.
In the app I have a `remember logged in user` option that will keep the access token for future use. But in most cases as most devices will be in shared rooms I think people want their account info removed after export (removeAccount).

This is a blocking issue for my next release so I hope it can be looked into soon.

**Comment by alfetch** [comment]
I agree. I have also noticed the same issue.

**Comment by danieldobalian** [comment]
Thanks for revisiting this issue. We're going to reflect on some ideas (both short / long term) and will get back to you.  

What's the timeline for your next release? Full disclosure, we're primarily focused on our next release which is allowing MSAL apps to integrate with the Auth brokers (Microsoft Authenticator and Intune Company Portal) to allow for better SSO and Device Management. 

Most likely, we'll look at refactoring sign out next after that release.

**Comment by heidijinxujia** [comment]
One migration for this issue is to calling the ` CookieManager.getInstance().removeAllCookie()` and  `removeAllCookies(ValueCallback<Boolean> callback)` API inside the app. @alfetch This will remove all accounts in the native webview cookies.

```java
public void onRemoveUserClicked(final String username) {
        mApplication.getAccounts(new PublicClientApplication.AccountsLoadedListener() {
            @Override
            public void onAccountsLoaded(List<IAccount> accountsToRemove) {
                for (final IAccount accountToRemove : accountsToRemove) {
                    if (TextUtils.isEmpty(username) || accountToRemove.getUsername().equalsIgnoreCase(username.trim())) {
                        mApplication.removeAccount(accountToRemove);

                        //You can add the following code to remove the webview cookie.
                        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
                            CookieManager.getInstance().removeAllCookies(new ValueCallback<Boolean>() {
                                // a callback which is executed when the cookies have been removed
                                @Override
                                public void onReceiveValue(Boolean aBoolean) {
                                    Log.d(TAG, "Cookie removed: " + aBoolean);
                                }
                            });
                        } else {
                            CookieManager.getInstance().removeAllCookie();
                        }
                    }
                }
            }
        });
    }
``

**Comment by Glennmen** [comment]
@danieldobalian I want to release it in about a month but generally it depends on management decision. I can try to stretch it a little longer but worse case scenario I would need to temporarily disable the feature.

**Comment by danieldobalian** [comment]
Thanks @Glennmen.  In the short term, I recommend following @heidijinxujia's recommendation above.

**Comment by Glennmen** [comment]
@danieldobalian @heidijinxujia Thanks for the suggestion, I will try the workaround and report back if it works correctly in my case.

**Comment by Glennmen** [comment]
@heidijinxujia Thanks for the workaround! It works perfectly.
Btw you don't need the callback if you aren't really using it:
```java
// Remove all webview cookies
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
	CookieManager.getInstance().removeAllCookies(null);
} else {
	CookieManager.getInstance().removeAllCookie();
}
```

I would still like to keep this issue open as a placeholder for a build in long term solution.

**Comment by alfetch** [comment]
<3 Perfect
