### ISSUE TITLE
onActivityResult() getting called right after startActivityForResult() on low Android API

### ISSUE THREAD

**Issue by scscgit** [AzureAD/microsoft-authentication-library-common-for-android#334]
There has been accepted a pull request https://github.com/AzureAD/microsoft-authentication-library-common-for-android/pull/247 which has probably fixed some Huawei browser auth flow bug, but this causes another compatibility issue with a low Android API (tested on Sony Xperia SP, API 18), as the onActivityResult() is called within our custom app right after the library invokes startActivityForResult(). The int requestCode is AuthorizationStrategy.BROWSER_FLOW, but the Intent data is null, which we pass to the PublicClientApplication.handleInteractiveRequestRedirect() and get the onError callback.

We could handle this by using a null check, but any further attempt to log in using the browser is ignored, as the callback no longer works - our onActivityResult() is no longer getting called at all. According to an older StackOverflow post, there is a consensus that startActivityForResult() mustn't be used if an activity is being launched as a singleInstance or singleTask: < https://stackoverflow.com/questions/7910840/android-startactivityforresult-immediately-triggering-onactivityresult >.

The developer can always override this in app manifest, so a fix (which should be at least mentioned in README) could be for example:
\<activity android:name="com.microsoft.identity.common.internal.providers.oauth2.AuthorizationActivity"
android:launchMode="standard" tools:replace="android:launchMode" />
But if the Android guidelines advise to use the default "standard" launchMode, maybe it would make more sense to let Huawei developers use this "hotfix" instead of everyone else by default.

Please make a decision that will make it easier for others to handle this problem in the future - instead of breaking Huawei, you could detect this issue during runtime and throw a user friendly exception explaining that the launchMode must be overridden. Maybe some other flags could be also used within startActivityForResult() to handle this issue, e.g. by adding some low API check. My pull request that simply reverts the Huawei hotfix is: https://github.com/AzureAD/microsoft-authentication-library-common-for-android/pull/333

**Comment by iambmelt** [comment]
This is a pre-release issue; the need for end-devs to override `onActivityResult` has been removed as of 1.0.x
