### ISSUE TITLE
Extra Query params are not set to Token request

### ISSUE THREAD

**Issue by kreedula** [AzureAD/microsoft-authentication-library-common-for-android#365]
`TokenRequest` or any of it's Sub classes  like `MicrosoftTokenRequest` , `MicrosoftStsTokenRequest` doesn' have a way to set extra query parameters, thus they are not sent to token endpoint when they are set to the  acquire token request.

Extra qp are successfully sent to auth endpoint though.

**Comment by iambmelt** [comment]
There is an ADO item tracking this already - closing.
https://identitydivision.visualstudio.com/Engineering/_workitems/edit/1443931
