### ISSUE TITLE
ADAL Storage Encryption Keys can in some scenarios be corrupt/invalid....

### ISSUE THREAD

**Issue by shoatman** [AzureAD/microsoft-authentication-library-common-for-android#40]
Need to investigate how to detect and respond to this occurrence without necessarily removing existing related cache state.

**Comment by iambmelt** [comment]
Related: https://github.com/AzureAD/microsoft-authentication-library-common-for-android/issues/480
Closed by: https://github.com/AzureAD/microsoft-authentication-library-common-for-android/pull/481
