### ISSUE TITLE
Allow users to customize the CustomTab colors

### ISSUE THREAD

**Issue by joshfriend** [AzureAD/microsoft-authentication-library-common-for-android#427]
The customtabs support library offers a few options to customize the [primary](https://developer.android.com/reference/android/support/customtabs/CustomTabsIntent.Builder.html#setToolbarColor(int)) and [secondary](https://developer.android.com/reference/android/support/customtabs/CustomTabsIntent.Builder.html#setsecondarytoolbarcolor) colors of the toolbar.

The `CustomTabsIntent.Builder` is always buried inside a method so these customization options are not currently accessible. 

One possible way these options could be supplied is through a `Bundle` when configuring the `PublicClientApplication` instance since all of the options in the `CustomTabsIntent.Builder` map down [to string keys in a intent bundle anyways](https://developer.android.com/reference/android/support/customtabs/CustomTabsIntent#extra_toolbar_color)

**Comment by joshfriend** [comment]
Oops, i created this in the wrong project by accident. Could one of the maintainers move it over to https://github.com/AzureAD/microsoft-authentication-library-for-android please?

**Comment by shoatman** [comment]
Thanks Josh.  We'll create in MSAL and add a pointer back to this issue.

**Comment by joshfriend** [comment]
Github [added a move option](https://help.github.com/en/articles/transferring-an-issue-to-another-repository) recently that you can use to transfer issues between repos.

**Comment by iambmelt** [comment]
Tracking here, closing

https://github.com/AzureAD/microsoft-authentication-library-for-android/issues/57
