### ISSUE TITLE
Gradle version in SDK needs upgrade. Does not work with Java > 10

### ISSUE THREAD

**Issue by brandwe** [AzureAD/microsoft-authentication-library-common-for-android#505]
When building with a Java SDK that is below 11, the developer will receive the following error:

_Gradle: Could not determine java version from '11.0.2'_

The grade included in the SDK e.g. `gradle/wrapper/gradle-wrapper.properties` points to `distributionUrl=https\://services.gradle.org/distributions/gradle-4.6-all.zip`. This an old version of Gradle and causes anyone uses Java SDKs released since September 2018 to fail.

See: https://stackoverflow.com/questions/54358107/gradle-could-not-determine-java-version-from-11-0-2

**Comment by iambmelt** [comment]
Resolved by #1150
