### ISSUE TITLE
Move ClientInfo from MSAL to common

### ISSUE THREAD

**Issue by shoatman** [AzureAD/microsoft-authentication-library-common-for-android#6]
- ClientInfo will become part of the response on the Azure AD v1 endpoint
- Need to update MSAL to leverage common

**Comment by iambmelt** [comment]
I'll pick this up @shoatman -- Will likely do this in two PRs: [first PR](https://github.com/iambmelt/microsoft-authentication-library-for-android/issues/1) will establish submodule dependency, once that merges I'll set this up.

**Comment by iambmelt** [comment]
Completed by 584c9bbcad7d1fe7923209557e51fce06d01c24b
