### ISSUE TITLE
review throwing exceptions on IDP response

### ISSUE THREAD

**Issue by amishra-dev** [AzureAD/microsoft-authentication-library-common-for-android#71]
IDP response should be validated upfront so that we are not throwing exceptions all over the place.

**Comment by shoatman** [comment]
@addev-ashish @iambmelt - I sent you both an email on this topic.  I'd suggest introducing authorization and token response object validation to OAuth2Strategy and then implementing on the AzureActiveDirectory and Microsoft STS derivations.  (Possibly a Microsoft derivation if much of this is common between the two)

**Comment by iambmelt** [comment]
This is now the responsibility of the strategy object. Closing as noop
