### ISSUE TITLE
Memory leak in CommandDispatcher

### ISSUE THREAD

**Issue by shahzaibj** [AzureAD/microsoft-authentication-library-common-for-android#711]
Commands are not being removed from the `sExecutingCommands` Set after they have been executed. 

This is happening because the code modifies the command after it has been added to the set, and hence the hashcode changes. Now when remove is called to remove the command from the set upon completion of the command, java is unable to remove the command as the hashcode has changed and does not match with any of the commands that are in the Hash Set.

This means that the Hash Set's memory is not cleared and can grow with linearly with new token requests.

**Comment by iambmelt** [comment]
Closing. This has been fixed
