### ISSUE TITLE
Review Inheritance Hierarchy of MicrosoftStsAccount

### ISSUE THREAD

**Issue by iambmelt** [AzureAD/microsoft-authentication-library-common-for-android#73]
Per earlier conversation, do we want `MicrosoftStsAccount` to `extend AzureActiveDirectoryAccount`?

**Comment by shoatman** [comment]
I took at look at this.  I think we should follow the pattern that we've introduced for other shared artifacts.  That is introduce a "MicrosoftAccount" (as possibly confusing as that could be) and have both MicrosoftSTSAccount and AzureActiveDirectoryAccount inherit from that.  Feel free to assign this refactoring to me if you like.

**Comment by shoatman** [comment]
@iambmelt FYI - Added comment.

**Comment by iambmelt** [comment]
Done, see #72 @ b345ffe8fa6a4a371294e00b4f45624b040056a4
