### ISSUE TITLE
Missing Copyright Statement across the Library

### ISSUE THREAD

**Issue by heidijinxujia** [AzureAD/microsoft-authentication-library-common-for-android#79]
I think we are missing the copyright statement for each class. Please confirm. @shoatman @iambmelt

**Comment by iambmelt** [comment]
We missing it in a number of files. Do we still have to do this on a per-file basis even if we have it in the repo's root? I can follow up w/ CLA on this mattter....

/cc @shoatman

**Comment by iambmelt** [comment]
Yep, we gotta do this

**Comment by iambmelt** [comment]
@heidijinxujia I'll take care of this, you'll be on CR
