### ISSUE TITLE
Allow WebView Zoom Toggle

### ISSUE THREAD

**Issue by arislomovic** [AzureAD/microsoft-authentication-library-common-for-android#803]
WebView Zoom controls should be configurable instead of hardcoded to be always on.

**Comment by arislomovic** [comment]
I tried to fix this too. 

https://github.com/AzureAD/microsoft-authentication-library-common-for-android/pull/796

**Comment by rpdome** [comment]
#796  #808 

@arislomovic Given that this is a behavior change/enhancement in the library, I'll have to run this through our team before accepting any changes.

There are four fields that you'd like to be customizable
setLoadWithOverviewMode
setDomStorageEnabled
setUseWideViewPort
setBuiltInZoomControls

Could you please provide the reason for each settings why you would like them to be off? 

Thanks.

**Comment by arislomovic** [comment]
@rpdome  I actually don't care about 
setLoadWithOverviewMode
setDomStorageEnabled
setUseWideViewPort

But added them, because I thought it'd be helpful for the webview to be configurable. 

But I would like to add: 

  private boolean zoomControlsEnabled = true;
  private boolean zoomEnabled = true;

just for the zoom. I made a new PR to reflect this change.

As for the reason, we think the zoom controls being visible detracts from the aesthetics of the app flow, and we would rather not have the user be able to zoom at all. Is there a reason that those settings are hard-coded?

**Comment by rpdome** [comment]
From the top of my head - accessibility.

**Comment by arislomovic** [comment]
Understood. The zoom issue, though, in my opinion should be customizable, as it's pretty harmless.  Maybe change the WebViewSettings class to ZoomControls? I don't know, but it's just a thought.

**Comment by rpdome** [comment]
@arislomovic For now, we'll be putting this feature request in the backlog. This capability might be configurable as part of the config file.

@hamiltonha fyi.

**Comment by shoatman** [comment]
Hi @arislomovic, as discussed feel free to update your PR to use the PublicClientConfiguration class in MSAL to expose this as a configuration setting.  Since we're trying to get this done quickly I suggest exposing something like: WebviewZoomControlsEnabled as a boolean.  Then you need to make this available when the authorization strategy is invoked, which you can do by adding this value to the OperationParameters class and updating the OperationParametersAdapter to flow it through.

**Comment by arislomovic** [comment]
@shoatman Thanks!

**Comment by arislomovic** [comment]
@shoatman 
is this more what you had in mind? 
https://github.com/AzureAD/microsoft-authentication-library-common-for-android/pull/818

**Comment by shoatman** [comment]
Yes.  I'm guessing you'll have a separate change for MSAL as well.  Thanks!

**Comment by arislomovic** [comment]
Yes. I will get that done tomorrow.

**Comment by shoatman** [comment]
Awesome.  Thanks Ari!

**Comment by arislomovic** [comment]
@shoatman 
https://github.com/AzureAD/microsoft-authentication-library-for-android/pull/925
here is the other PR. It failed, because the commons is not up to date yet, but it is there.
