### ISSUE TITLE
Not able to clear cookies on logout

### ISSUE THREAD

**Issue by mrudulamrudu** [AzureAD/microsoft-authentication-library-common-for-android#814]
I am trying to logout and clear all data using logout, but when I login in again, old account is in cookies.

I am using below code to logout :
```
 mSingleAccountApp.signOut(new ISingleAccountPublicClientApplication.SignOutCallback() {
                    @Override
                    public void onSignOut() {
                    }

                    @Override
                    public void onError(@NonNull MsalException exception) {
                    }
                });
            }
```

How do I reset the cookie when logged out ?

**Comment by rpdome** [comment]
Hi @mrudulamrudu. I'll follow up on this one and keep you updated.

**Comment by rpdome** [comment]
#762

**Comment by mrudulamrudu** [comment]
@rpdome Any update on this ?

**Comment by rpdome** [comment]
Hi @mrudulamrudu 

There are three possible scenarios that sign-in can be done.
1. MSAL webview "without" broker app.
- The calling app can clear cookies through CookieManager.

2. MSAL Browser (CustomTabs) "without" broker app.
- The user will have to remove cookies in Chrome. There is no way to do this programmatically.

3. MSAL with broker app.
- The user will have to "clear cache" from the Broker app (Authenticator/Company Portal). There is no way to do this programmatically.

Thanks,
Dome

**Comment by mrudulamrudu** [comment]
@rpdome How do I trigger the WebView to signout ? Is there any method available for that ? In IOS we are using signoutWithAccount:(nonnull MSALAccount *)account which triggers the WebView.

**Comment by rpdome** [comment]
MSAL on Android currently doesn't expose any API for that.

However, since WebView's cookie jar is 'per app', you can do one of the following

1. You can invoke [cookieManager.removeAllCookies](https://developer.android.com/reference/android/webkit/CookieManager#removeAllCookies(android.webkit.ValueCallback%3Cjava.lang.Boolean%3E))().

2. If you have a webview in your code, you can [send a sign out request](https://login.microsoftonline.com/common/oauth2/v2.0/logout).

**Comment by mrudulamrudu** [comment]
@rpdome I don't have any webview instance as I am using the below code for sign in.
```

 PublicClientApplication.createSingleAccountPublicClientApplication(this,
                R.raw.auth_config_single_account,
                new IPublicClientApplication.ISingleAccountApplicationCreatedListener() {
                    @Override
                    public void onCreated(ISingleAccountPublicClientApplication application) {
                        /*
                         * This test app assumes that the app is only going to support one account.
                         * This requires "account_mode" : "SINGLE" in the config json file.
                         **/
                        mSingleAccountApp = application;
                        loadAccount();
                    }

                    @Override
                    public void onError(MsalException exception) {
                        displayError(exception);
                    }
                });
   if (mSingleAccountApp == null) {
            return;
        }
        mSingleAccountApp.signIn(this, null, new String[]{"user.read"}, getAuthInteractiveCallback());
```
the code is pushing a webview to signin, even after signout the previous account is still logged in.

**Comment by mrudulamrudu** [comment]
Any update on this ?

**Comment by rpdome** [comment]
In that case you can go with the option #1 above. It's an Android API.

Please note that MSAL will use Broker **by default**, if any of the Broker apps is installed (Microsoft Authenticator/Company Portal).

**Comment by mrudulamrudu** [comment]
I tried resetting the cookies using cookie manager it still dint sign me out. I see my account is still logged in when I try to sign in again (It didn't ask me for my password).

```
 CookieManager cookieManager = CookieManager.getInstance();
                cookieManager.removeAllCookies(new ValueCallback<Boolean>() {
                    @Override
                    public void onReceiveValue(Boolean aBoolean) {
                    }
                });
```

How does clearing cookies helps when I don't have a webview instance ? aBoolean is always returning me false.

**Comment by rpdome** [comment]
Can you check if you're using WebView or Browser (Default) in your configuration file?

**Comment by mrudulamrudu** [comment]
"authorization_user_agent" : "DEFAULT"

**Comment by rpdome** [comment]
That means it's using Browser (Chrome Custom Tabs). In that case there is nothing we can do from the cookies point of view (as it's owned by Chrome).

Clearing cookie would require explicit action by user.

Alternatively, you can launch Chrome with the [sign out request](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-protocols-oidc#send-a-sign-out-request).

**Comment by mrudulamrudu** [comment]
Changing "authorization_user_agent" : "WEBVIEW" has resolved the issue. After signout I am being promoted to enter my password. Thank you so much !
