### ISSUE TITLE
 java.lang.NullPointerException: throw with null exception - Exception for release apks with progaurd enabled.

### ISSUE THREAD

**Issue by mrudulamrudu** [AzureAD/microsoft-authentication-library-common-for-android#826]
java.lang.NullPointerException: throw with null exception
        at com.microsoft.identity.client.u.b.a(Unknown Source:3)
        at com.microsoft.identity.client.p.a(SourceFile:21)
        at com.microsoft.identity.client.p.d(SourceFile:6)
        at com.microsoft.identity.client.p.<init>(SourceFile:6)
        at com.microsoft.identity.client.s.<init>(SourceFile:1)
        at com.microsoft.identity.client.p$d.a(SourceFile:6)
        at com.microsoft.identity.client.p$d.a(SourceFile:1)
        at c.d.a.a.f.d.e$b.run(SourceFile:3)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7762)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1047)

**Comment by shahzaibj** [comment]
@mrudulamrudu Can you provide a bit more information like which library are you using? MSAL or ADAL? and which version?

Also When do you see this issue? Does it happen when you call a specific method in our library?

**Comment by mrudulamrudu** [comment]
@shahzaibj I am using **msal:1.2.0**
The issue happens When I open the Activity with msal login code.
I am calling the below method in my onCreate()

 // Creates a PublicClientApplication object with res/raw/auth_config_single_account.json
     ```
   PublicClientApplication.createSingleAccountPublicClientApplication(this,
                R.raw.auth_config_single_account,
                new IPublicClientApplication.ISingleAccountApplicationCreatedListener() {
                    @Override
                    public void onCreated(ISingleAccountPublicClientApplication application) {
                        *//*
                         * This test app assumes that the app is only going to support one account.
                         * This requires "account_mode" : "SINGLE" in the config json file.
                         **//*
                        mSingleAccountApp = application;
                        loadAccount();
                    }

                    @Override
                    public void onError(MsalException exception) {
                        displayError(exception);
                    }
                });
```
this is only happening for release APKs.

**Comment by mrudulamrudu** [comment]
Do I need to provide a release hash key before creating a release APK ? I suspect if its causing the app to crash ?

**Comment by shahzaibj** [comment]
Are you referring the package signature? You will need to provide the redirect_uri  in the config file as well as in the AndroidManifest. The redirect uri will need to contain the package name as well as the signature. See these instructions: https://github.com/AzureAD/microsoft-authentication-library-for-android#using-msal Did you follow these when integrating with MSAL?

**Comment by mrudulamrudu** [comment]
@shahzaibj Thanks for the response. I have followed the steps from the same link and the app works fine when I create a debug build, I am able to sign in to my account using msal and access the graph request as well. But app crashes on launch with the mentioned crash when I create a release APK with Keystore. I don't see any other errors in the logcat apart from the above crash.

**Comment by shahzaibj** [comment]
Did you change the redirect uri for the release APK? The release APK will be signed with a different key, and hence result in a different package signature. Did you make sure to add two different redirect uri in the portal, one for debug and one for release? and also update according in your app based on whether the build is a debug build of release build?

**Comment by mrudulamrudu** [comment]
No, I haven't done that. How do I create a Redirect URI for release APK ? Could you please give me a link for that ?

**Comment by shahzaibj** [comment]
You can go in the Azure Portal->app registrations->select your app
->Now go to the Authentication tab

You will see option to add another redirect uri, click that it will ask you for your apps package name and singature hash and will generate a redirect uri based on those values for you.

It will also provide instructions on how to obtain the signature hash, but you can also refer to this FAQ: https://github.com/AzureAD/microsoft-authentication-library-for-android/wiki/MSAL-FAQ

**Comment by mrudulamrudu** [comment]
@shahzaibj I have followed the steps and created a new package hash using Keystore, added it in the portal and in the app as well. The app still crashes with the same NullPointer exception.

**Comment by shahzaibj** [comment]
So I guess it is a Pro Guard issue then. I found this similar issue here and may be this can help you. 
https://github.com/AzureAD/microsoft-authentication-library-for-android/issues/513

I'll see if I can find something else related to Pro Guard in the past

**Comment by mrudulamrudu** [comment]
@shahzaibj 
-keep public enum com.microsoft.identity.client.configuration.AccountMode { *; }
-keep public class com.microsoft.identity.client.configuration.HttpConfiguration { *; }
-keep public class com.microsoft.identity.client.configuration.LoggerConfiguration { *; }

Adding them to progaurd fixed the issue. Thank you so much !
