### ISSUE TITLE
KeyPairGeneratorSpec deprecated

### ISSUE THREAD

**Issue by shoatman** [AzureAD/microsoft-authentication-library-common-for-android#849]
https://developer.android.com/reference/android/security/KeyPairGeneratorSpec

**Comment by iambmelt** [comment]
ADO Tracking (corpnet reqd):
- https://identitydivision.visualstudio.com/Engineering/_workitems/edit/1226180

**Comment by iambmelt** [comment]
No code changes necessary. This code path is only used by PoP and the implementation is backwards/forwards compat down to API 18:
https://github.com/AzureAD/microsoft-authentication-library-common-for-android/blob/dev/common/src/main/java/com/microsoft/identity/common/internal/platform/DevicePopManager.java#L1263-L1266
