### ISSUE TITLE
BUILD.CPU_ABI deprecated

### ISSUE THREAD

**Issue by shoatman** [AzureAD/microsoft-authentication-library-common-for-android#850]
https://developer.android.com/reference/android/os/Build#CPU_ABI

**Comment by iambmelt** [comment]
ADO Tracking (corpnet reqd):
- https://identitydivision.visualstudio.com/Engineering/_workitems/edit/1226179

**Comment by iambmelt** [comment]
@gitaumoses4 Assigning to you, as you have picked up the ADO ticket

**Comment by gitaumoses4** [comment]
Fixed in afaa031c6b94b255cc53482f734f50dde496bc4e
