### ISSUE TITLE
webviewclient onReceivedError deprecated

### ISSUE THREAD

**Issue by shoatman** [AzureAD/microsoft-authentication-library-common-for-android#855]
https://developer.android.com/reference/android/webkit/WebViewClient#onReceivedError(android.webkit.WebView,%20int,%20java.lang.String,%20java.lang.String)

**Comment by iambmelt** [comment]
ADO Tracking (corpnet reqd):
- https://identitydivision.visualstudio.com/Engineering/_workitems/edit/1226175

**Comment by iambmelt** [comment]
Fixed by:
- https://github.com/AzureAD/microsoft-authentication-library-common-for-android/pull/1197
- https://github.com/AzureAD/azure-activedirectory-library-for-android/pull/1580
- https://github.com/AzureAD/microsoft-authentication-library-for-android/pull/1282
