### ISSUE TITLE
versionCode in PackageInfo has been deprecated

### ISSUE THREAD

**Issue by shoatman** [AzureAD/microsoft-authentication-library-common-for-android#863]
https://developer.android.com/reference/android/content/pm/PackageInfo#versionCode

**Comment by iambmelt** [comment]
ADO Tracking (corpnet reqd):
- https://identitydivision.visualstudio.com/Engineering/_workitems/edit/1226174

**Comment by ravisorathiya** [comment]
**Extension Function on Context to get Application Version code**

    fun Context.getAppVersionCode(): Int {
            val packageInfo = this.packageManager.getPackageInfo(this.packageName, 0)
            return PackageInfoCompat.getLongVersionCode(packageInfo).toInt()
        }
