### ISSUE TITLE
new flag skipPowerOptimizationCheck is named and documented incorrect

### ISSUE THREAD

**Issue by slowcar** [AzureAD/microsoft-authentication-library-common-for-android#904]
see https://github.com/AzureAD/microsoft-authentication-library-common-for-android/blob/dev/common/src/main/java/com/microsoft/identity/common/adal/internal/net/HttpWebRequest.java

@param skipPowerOptimizationCheck : boolean to skip power optimization check

if the flag is set to true the check is done, if it is set to false it is skipped.

The behavior is correct (power_opt_check_for_network_req_enabled set to false in the msal_config.json skips the power check), its just the name and javadoc that is incorrect.

**Comment by iambmelt** [comment]
Thanks @slowcar -- we'll get this fixed in a future release

**Comment by iambmelt** [comment]
Introduced in https://github.com/AzureAD/microsoft-authentication-library-common-for-android/pull/894

**Comment by benjaminuggla** [comment]
Hi,
I'm facing the same issue as the author and have a lot of problems with dropped requests.

I have been looking around where I can specify this skipPowerOptimiationCheck setting but can't find it. @slowcar is talking about msal_config.json but I find no documentation about that file. Can you please provide information in how to solve this?

Thanks
Benjamin

**Comment by slowcar** [comment]
Hi Ben,
the documentation about the json file is here: https://docs.microsoft.com/azure/active-directory/develop/msal-configuration , it is linked from the main library github (this here is the common library): https://github.com/AzureAD/microsoft-authentication-library-for-android

the documentation does not have the flag listed yet, but it works correctly.
