### ISSUE TITLE
Duplicate command errors

### ISSUE THREAD

**Issue by slowcar** [AzureAD/microsoft-authentication-library-common-for-android#905]
When executing multiple workers concurrently i get duplicate command errors from time to time.

Responsible is the code added here: https://github.com/AzureAD/microsoft-authentication-library-common-for-android/commit/abdcee2c6aec85b43cf5d53ce763a4151efbb494

I would like to be able to retrieve the current token from multiple threads/workers at once.

**Comment by iambmelt** [comment]
Fixed in [2.0.1](https://github.com/AzureAD/microsoft-authentication-library-for-android/releases/tag/v2.0.1)
